#!/usr/bin/env bash
# browser-harness-pin.sh — version pinning for the cloned browser-harness.
#
# Why pin: the harness is installed via `uv tool install -e .` from a local
# clone at $BROWSER_HARNESS_REPO. `git pull` inside that clone silently
# changes what every specialist sees next time they invoke `browser-harness`.
# Agents could run on a new version without any diff surface. That's a real
# risk when the harness drives browser automation against our Chrome.
#
# Upstream browser-harness itself has a --doctor + --update flow, but it only
# checks GitHub's *release tags* (latest release), not specific commits, and
# it upgrades via its own uv-tool-install path that assumes we don't have a
# local editable clone. Our setup is different: local clone + editable
# install, so we can contribute back. We need our own pinning discipline.
#
# This script maintains a lockfile at $AGENT_CO_ROOT/.browser-harness-lock
# with the blessed commit SHA. Subcommands:
#
#   status   — show installed version, clone HEAD, locked SHA, drift state
#   check    — exit non-zero if clone HEAD drifts from the locked SHA
#   pin      — record current clone HEAD as the blessed SHA
#   upgrade  — pull upstream, re-install, update lockfile; shows changelog diff
#
# Safe to run repeatedly. No git destructive ops (no reset --hard, no force-push).

set -euo pipefail

BROWSER_HARNESS_REPO="${BROWSER_HARNESS_REPO:-$HOME/Projects/browser-harness}"
AGENT_CO_ROOT="${AGENT_CO_ROOT:-$HOME/agent-co}"
LOCKFILE="$AGENT_CO_ROOT/.browser-harness-lock"
UV_BIN="${UV_BIN:-$HOME/.local/bin/uv}"

cmd="${1:-status}"
shift || true

if [ ! -d "$BROWSER_HARNESS_REPO/.git" ]; then
  echo "error: $BROWSER_HARNESS_REPO is not a git clone" >&2
  exit 2
fi

get_head_sha() {
  git -C "$BROWSER_HARNESS_REPO" rev-parse HEAD
}

get_head_short() {
  git -C "$BROWSER_HARNESS_REPO" rev-parse --short HEAD
}

get_locked_sha() {
  [ -f "$LOCKFILE" ] && grep '^commit_sha=' "$LOCKFILE" | cut -d= -f2- || echo ""
}

get_installed_version() {
  "$UV_BIN" tool list 2>/dev/null | awk '/^browser-harness/ { print $2 }'
}

write_lock() {
  local sha="$1"
  local note="${2:-pinned via browser-harness-pin.sh}"
  cat > "$LOCKFILE" <<EOF
# agent-co browser-harness pinning lockfile
# Generated by scripts/browser-harness-pin.sh
# Do NOT edit manually — use \`browser-harness-pin.sh pin\` or \`upgrade\`.

commit_sha=$sha
locked_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
pinned_by=$(whoami)
repo_path=$BROWSER_HARNESS_REPO
notes=$note
EOF
}

case "$cmd" in
  status)
    head=$(get_head_sha)
    locked=$(get_locked_sha)
    installed=$(get_installed_version)
    echo "browser-harness status"
    echo "  installed version : ${installed:-<not installed via uv>}"
    echo "  clone HEAD        : $head"
    echo "  locked SHA        : ${locked:-<no lock>}"
    if [ -n "$locked" ] && [ "$head" != "$locked" ]; then
      echo "  drift             : YES — clone ahead/behind locked SHA"
      echo "  action            : run 'browser-harness-pin.sh check' or 'upgrade'"
    elif [ -z "$locked" ]; then
      echo "  drift             : N/A (no lock yet — run 'pin' to create one)"
    else
      echo "  drift             : no"
    fi
    ;;

  check)
    head=$(get_head_sha)
    locked=$(get_locked_sha)
    if [ -z "$locked" ]; then
      echo "warning: no lockfile at $LOCKFILE — run 'pin' to establish baseline" >&2
      exit 3
    fi
    if [ "$head" != "$locked" ]; then
      echo "DRIFT: clone HEAD ($head) differs from locked SHA ($locked)" >&2
      echo "" >&2
      echo "Recent clone commits past the lock:" >&2
      git -C "$BROWSER_HARNESS_REPO" log --oneline "$locked..HEAD" 2>/dev/null | head -10 >&2
      echo "" >&2
      echo "To adopt the current clone state: scripts/browser-harness-pin.sh pin" >&2
      echo "To roll the clone back to the lock: git -C $BROWSER_HARNESS_REPO checkout $locked" >&2
      exit 1
    fi
    echo "OK: clone matches locked SHA ($locked)"
    ;;

  pin)
    head=$(get_head_sha)
    note="${1:-manual pin of current clone HEAD}"
    write_lock "$head" "$note"
    echo "pinned to $head"
    echo "lockfile: $LOCKFILE"
    ;;

  upgrade)
    prev_locked=$(get_locked_sha)
    echo "fetching upstream..."
    git -C "$BROWSER_HARNESS_REPO" fetch --all --tags --quiet
    branch=$(git -C "$BROWSER_HARNESS_REPO" rev-parse --abbrev-ref HEAD)
    upstream_sha=$(git -C "$BROWSER_HARNESS_REPO" rev-parse "origin/$branch" 2>/dev/null || git -C "$BROWSER_HARNESS_REPO" rev-parse origin/main)
    current_sha=$(get_head_sha)

    if [ "$current_sha" = "$upstream_sha" ]; then
      echo "already at upstream HEAD ($current_sha)"
    else
      echo "changelog since current clone HEAD:"
      git -C "$BROWSER_HARNESS_REPO" log --oneline "$current_sha..$upstream_sha" | head -20
      echo ""

      # Verify the working tree is clean before pulling
      if ! git -C "$BROWSER_HARNESS_REPO" diff --quiet HEAD --; then
        echo "error: working tree has uncommitted changes. Commit or stash before upgrading." >&2
        exit 4
      fi

      echo "pulling into $BROWSER_HARNESS_REPO ..."
      git -C "$BROWSER_HARNESS_REPO" pull --ff-only
    fi

    new_sha=$(get_head_sha)
    echo "re-installing via uv tool install -e ..."
    (cd "$BROWSER_HARNESS_REPO" && "$UV_BIN" tool install -e . 2>&1 | tail -3)

    if [ -z "$prev_locked" ] || [ "$prev_locked" != "$new_sha" ]; then
      write_lock "$new_sha" "upgraded from ${prev_locked:-<unlocked>}"
      echo "lock updated: ${prev_locked:-<none>} -> $new_sha"
    else
      echo "lockfile already at $new_sha (no change)"
    fi

    echo ""
    echo "verify with: browser-harness --doctor"
    ;;

  *)
    cat <<EOF
usage: $0 <command>

commands:
  status    show installed version + clone HEAD + locked SHA + drift state
  check     exit non-zero if clone drifts from lock (for CI / pre-commit)
  pin       record current clone HEAD as the blessed SHA
  upgrade   pull upstream, re-install, update lockfile

environment:
  BROWSER_HARNESS_REPO    default: \$HOME/Projects/browser-harness
  AGENT_CO_ROOT           default: \$HOME/agent-co
  UV_BIN                  default: \$HOME/.local/bin/uv

lockfile at: $LOCKFILE
EOF
    exit 1
    ;;
esac
