#!/usr/bin/env bash
# cc-version-check.sh — daily Claude Code drift + hook-firing validation.
#
# Fired by the agentco-cc-health-check.timer systemd unit at 07:00 daily.
#
# What it does:
#   1. Read pinned version from $AGENT_CO_ROOT/.claude-code-lock
#   2. Get currently-installed version via `claude --version`
#   3. Run a synthetic hook-firing test (spawn claude -p with a marker prompt,
#      then query memory.messages for the marker within a few seconds to confirm
#      the Stop hook persisted the turn)
#   4. POST results to relay's /cc-health-check endpoint
#   5. Relay handles: DB logging, notify_all on drift, spawn research claude
#
# Subcommands:
#   check  — run the full check (default)
#   bless  — adopt the currently-installed version into the lockfile
#   last   — show the last N health check rows from the DB
#
# Safe to run repeatedly. No destructive actions.

set -euo pipefail

AGENT_CO_ROOT="${AGENT_CO_ROOT:-$HOME/agent-co}"
LOCKFILE="$AGENT_CO_ROOT/.claude-code-lock"
RELAY_URL="${AGENTCO_RELAY_URL:-http://localhost:3456}"
ENV_FILE="$AGENT_CO_ROOT/agent-company/.env"

cmd="${1:-check}"

get_pinned_version() {
  [ -f "$LOCKFILE" ] && grep '^pinned_version=' "$LOCKFILE" | cut -d= -f2- | tr -d ' '
}

get_installed_version() {
  # `claude --version` outputs e.g. "2.1.118 (Claude Code)"
  claude --version 2>/dev/null | awk '{print $1}' || echo "unknown"
}

get_relay_token() {
  [ -f "$ENV_FILE" ] && grep '^RELAY_SECRET=' "$ENV_FILE" | cut -d= -f2- || echo ""
}

run_hook_firing_test() {
  # Spawn claude -p with a marker; the Stop hook should persist the turn to
  # memory.messages. Query the DB after a short wait to confirm.
  local marker="cc-hook-test-$(date +%s)-$$"
  local prompt="respond with exactly this one line and nothing else: $marker"

  # Fire the test session. Capture stdout (should echo the marker if all well,
  # but even if claude outputs nothing unusual the hook fires on Stop).
  timeout 60 claude --dangerously-skip-permissions -p "$prompt" >/dev/null 2>&1 || true

  # Give the Stop hook ~4s to POST to /persist-cli-turn.
  sleep 4

  # Query the DB for the marker in memory.messages from the last 90s.
  local found
  found=$(docker exec agentco_postgres psql -U agentco -d agentco -tA -c \
    "SELECT 1 FROM memory.messages WHERE platform='cli' AND content LIKE '%${marker}%' AND created_at > NOW() - INTERVAL '90 seconds' LIMIT 1;" 2>/dev/null || echo "")

  if [ -n "$found" ]; then
    # Cleanup: delete the test marker rows so they don't bloat memory.
    docker exec agentco_postgres psql -U agentco -d agentco -c \
      "DELETE FROM memory.messages WHERE content LIKE '%${marker}%';" >/dev/null 2>&1 || true
    echo "true:$marker"
  else
    echo "false:$marker"
  fi
}

case "$cmd" in
  check)
    pinned=$(get_pinned_version)
    installed=$(get_installed_version)
    if [ -z "$installed" ] || [ "$installed" = "unknown" ]; then
      echo "error: could not determine installed claude version" >&2
      exit 2
    fi
    if [ -z "$pinned" ]; then
      echo "warning: no pinned version in $LOCKFILE — treating as initial setup" >&2
      pinned=""
    fi

    echo "claude-code health check"
    echo "  pinned    : ${pinned:-<none>}"
    echo "  installed : $installed"

    hook_result=$(run_hook_firing_test)
    hooks_firing="${hook_result%%:*}"
    marker="${hook_result#*:}"
    echo "  hooks     : $hooks_firing  (marker=$marker)"

    notes="synthetic marker=$marker; ran from $(hostname)"
    token=$(get_relay_token)
    auth_header=""
    [ -n "$token" ] && auth_header="-H Authorization: Bearer $token"

    # POST to relay — use a heredoc for the payload to survive odd chars.
    payload=$(cat <<JSON
{
  "version": "$installed",
  "previousVersion": $([ -n "$pinned" ] && echo "\"$pinned\"" || echo "null"),
  "hooksFiring": $hooks_firing,
  "notes": "$notes"
}
JSON
)
    response=$(curl -sS -X POST "$RELAY_URL/cc-health-check" \
      -H "Content-Type: application/json" \
      ${auth_header} \
      -d "$payload" 2>&1 || echo '{"error":"curl failed"}')

    echo "  response  : $response"

    if [ "$hooks_firing" != "true" ] || ([ -n "$pinned" ] && [ "$installed" != "$pinned" ]); then
      echo "  status    : ESCALATED — relay will notify all channels + spawn research"
      exit 1
    else
      echo "  status    : OK"
      exit 0
    fi
    ;;

  bless)
    installed=$(get_installed_version)
    note="${2:-manually blessed current version}"
    cat > "$LOCKFILE" <<EOF
# agent-co Claude Code version pinning lockfile
# Generated by scripts/cc-version-check.sh
# Do NOT edit manually — use \`cc-version-check.sh bless\` to adopt a new version.

pinned_version=$installed
pinned_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
pinned_by=$(whoami)
notes=$note
EOF
    echo "blessed version $installed into $LOCKFILE"
    ;;

  last)
    n="${2:-10}"
    docker exec agentco_postgres psql -U agentco -d agentco -c \
      "SELECT checked_at, version, status, hooks_firing, notes FROM memory.cc_health_checks ORDER BY checked_at DESC LIMIT $n;"
    ;;

  *)
    cat <<EOF
usage: $0 <command>

commands:
  check    run the full version + hook-firing check; exits non-zero on drift
  bless [note]  adopt the currently-installed version into the lockfile
  last [n] show the last N health-check rows (default 10)

environment:
  AGENT_CO_ROOT       default: \$HOME/agent-co
  AGENTCO_RELAY_URL   default: http://localhost:3456

lockfile at: $LOCKFILE
EOF
    exit 1
    ;;
esac
